/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RejectedRouteImport } from './routes/rejected'
import { Route as PendingRouteImport } from './routes/pending'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ApplyRouteImport } from './routes/apply'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AcceptInviteRouteImport } from './routes/accept-invite'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as RequestCompanyIdRouteImport } from './routes/request.$companyId'
import { Route as AuthenticatedSettingsRouteImport } from './routes/_authenticated/settings'
import { Route as AuthenticatedRotationsRouteImport } from './routes/_authenticated/rotations'
import { Route as AuthenticatedMotorClubsRouteImport } from './routes/_authenticated/motor-clubs'
import { Route as AuthenticatedInboundEmailsRouteImport } from './routes/_authenticated/inbound-emails'
import { Route as AuthenticatedImpoundRouteImport } from './routes/_authenticated/impound'
import { Route as AuthenticatedDriverRouteImport } from './routes/_authenticated/driver'
import { Route as AuthenticatedBillingRouteImport } from './routes/_authenticated/billing'
import { Route as StatementAccountIdMonthRouteImport } from './routes/statement.$accountId.$month'
import { Route as ApiPublicInboundEmailRouteImport } from './routes/api/public/inbound-email'
import { Route as ApiPublicApprovalActionRouteImport } from './routes/api/public/approval-action'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RejectedRoute = RejectedRouteImport.update({
  id: '/rejected',
  path: '/rejected',
  getParentRoute: () => rootRouteImport,
} as any)
const PendingRoute = PendingRouteImport.update({
  id: '/pending',
  path: '/pending',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApplyRoute = ApplyRouteImport.update({
  id: '/apply',
  path: '/apply',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AcceptInviteRoute = AcceptInviteRouteImport.update({
  id: '/accept-invite',
  path: '/accept-invite',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const RequestCompanyIdRoute = RequestCompanyIdRouteImport.update({
  id: '/request/$companyId',
  path: '/request/$companyId',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedSettingsRoute = AuthenticatedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedRotationsRoute = AuthenticatedRotationsRouteImport.update({
  id: '/rotations',
  path: '/rotations',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMotorClubsRoute = AuthenticatedMotorClubsRouteImport.update({
  id: '/motor-clubs',
  path: '/motor-clubs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedInboundEmailsRoute =
  AuthenticatedInboundEmailsRouteImport.update({
    id: '/inbound-emails',
    path: '/inbound-emails',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedImpoundRoute = AuthenticatedImpoundRouteImport.update({
  id: '/impound',
  path: '/impound',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDriverRoute = AuthenticatedDriverRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedBillingRoute = AuthenticatedBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const StatementAccountIdMonthRoute = StatementAccountIdMonthRouteImport.update({
  id: '/statement/$accountId/$month',
  path: '/statement/$accountId/$month',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicInboundEmailRoute = ApiPublicInboundEmailRouteImport.update({
  id: '/api/public/inbound-email',
  path: '/api/public/inbound-email',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicApprovalActionRoute = ApiPublicApprovalActionRouteImport.update({
  id: '/api/public/approval-action',
  path: '/api/public/approval-action',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pending': typeof PendingRoute
  '/rejected': typeof RejectedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/impound': typeof AuthenticatedImpoundRoute
  '/inbound-emails': typeof AuthenticatedInboundEmailsRoute
  '/motor-clubs': typeof AuthenticatedMotorClubsRoute
  '/rotations': typeof AuthenticatedRotationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/request/$companyId': typeof RequestCompanyIdRoute
  '/api/public/approval-action': typeof ApiPublicApprovalActionRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/statement/$accountId/$month': typeof StatementAccountIdMonthRoute
}
export interface FileRoutesByTo {
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pending': typeof PendingRoute
  '/rejected': typeof RejectedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/billing': typeof AuthenticatedBillingRoute
  '/driver': typeof AuthenticatedDriverRoute
  '/impound': typeof AuthenticatedImpoundRoute
  '/inbound-emails': typeof AuthenticatedInboundEmailsRoute
  '/motor-clubs': typeof AuthenticatedMotorClubsRoute
  '/rotations': typeof AuthenticatedRotationsRoute
  '/settings': typeof AuthenticatedSettingsRoute
  '/request/$companyId': typeof RequestCompanyIdRoute
  '/': typeof AuthenticatedIndexRoute
  '/api/public/approval-action': typeof ApiPublicApprovalActionRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/statement/$accountId/$month': typeof StatementAccountIdMonthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/accept-invite': typeof AcceptInviteRoute
  '/admin': typeof AdminRoute
  '/apply': typeof ApplyRoute
  '/auth': typeof AuthRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/pending': typeof PendingRoute
  '/rejected': typeof RejectedRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/billing': typeof AuthenticatedBillingRoute
  '/_authenticated/driver': typeof AuthenticatedDriverRoute
  '/_authenticated/impound': typeof AuthenticatedImpoundRoute
  '/_authenticated/inbound-emails': typeof AuthenticatedInboundEmailsRoute
  '/_authenticated/motor-clubs': typeof AuthenticatedMotorClubsRoute
  '/_authenticated/rotations': typeof AuthenticatedRotationsRoute
  '/_authenticated/settings': typeof AuthenticatedSettingsRoute
  '/request/$companyId': typeof RequestCompanyIdRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/api/public/approval-action': typeof ApiPublicApprovalActionRoute
  '/api/public/inbound-email': typeof ApiPublicInboundEmailRoute
  '/statement/$accountId/$month': typeof StatementAccountIdMonthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/accept-invite'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/forgot-password'
    | '/pending'
    | '/rejected'
    | '/reset-password'
    | '/sitemap.xml'
    | '/billing'
    | '/driver'
    | '/impound'
    | '/inbound-emails'
    | '/motor-clubs'
    | '/rotations'
    | '/settings'
    | '/request/$companyId'
    | '/api/public/approval-action'
    | '/api/public/inbound-email'
    | '/statement/$accountId/$month'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/accept-invite'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/forgot-password'
    | '/pending'
    | '/rejected'
    | '/reset-password'
    | '/sitemap.xml'
    | '/billing'
    | '/driver'
    | '/impound'
    | '/inbound-emails'
    | '/motor-clubs'
    | '/rotations'
    | '/settings'
    | '/request/$companyId'
    | '/'
    | '/api/public/approval-action'
    | '/api/public/inbound-email'
    | '/statement/$accountId/$month'
  id:
    | '__root__'
    | '/_authenticated'
    | '/accept-invite'
    | '/admin'
    | '/apply'
    | '/auth'
    | '/forgot-password'
    | '/pending'
    | '/rejected'
    | '/reset-password'
    | '/sitemap.xml'
    | '/_authenticated/billing'
    | '/_authenticated/driver'
    | '/_authenticated/impound'
    | '/_authenticated/inbound-emails'
    | '/_authenticated/motor-clubs'
    | '/_authenticated/rotations'
    | '/_authenticated/settings'
    | '/request/$companyId'
    | '/_authenticated/'
    | '/api/public/approval-action'
    | '/api/public/inbound-email'
    | '/statement/$accountId/$month'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AcceptInviteRoute: typeof AcceptInviteRoute
  AdminRoute: typeof AdminRoute
  ApplyRoute: typeof ApplyRoute
  AuthRoute: typeof AuthRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  PendingRoute: typeof PendingRoute
  RejectedRoute: typeof RejectedRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  RequestCompanyIdRoute: typeof RequestCompanyIdRoute
  ApiPublicApprovalActionRoute: typeof ApiPublicApprovalActionRoute
  ApiPublicInboundEmailRoute: typeof ApiPublicInboundEmailRoute
  StatementAccountIdMonthRoute: typeof StatementAccountIdMonthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rejected': {
      id: '/rejected'
      path: '/rejected'
      fullPath: '/rejected'
      preLoaderRoute: typeof RejectedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pending': {
      id: '/pending'
      path: '/pending'
      fullPath: '/pending'
      preLoaderRoute: typeof PendingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apply': {
      id: '/apply'
      path: '/apply'
      fullPath: '/apply'
      preLoaderRoute: typeof ApplyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/accept-invite': {
      id: '/accept-invite'
      path: '/accept-invite'
      fullPath: '/accept-invite'
      preLoaderRoute: typeof AcceptInviteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/request/$companyId': {
      id: '/request/$companyId'
      path: '/request/$companyId'
      fullPath: '/request/$companyId'
      preLoaderRoute: typeof RequestCompanyIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/settings': {
      id: '/_authenticated/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthenticatedSettingsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/rotations': {
      id: '/_authenticated/rotations'
      path: '/rotations'
      fullPath: '/rotations'
      preLoaderRoute: typeof AuthenticatedRotationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/motor-clubs': {
      id: '/_authenticated/motor-clubs'
      path: '/motor-clubs'
      fullPath: '/motor-clubs'
      preLoaderRoute: typeof AuthenticatedMotorClubsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/inbound-emails': {
      id: '/_authenticated/inbound-emails'
      path: '/inbound-emails'
      fullPath: '/inbound-emails'
      preLoaderRoute: typeof AuthenticatedInboundEmailsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/impound': {
      id: '/_authenticated/impound'
      path: '/impound'
      fullPath: '/impound'
      preLoaderRoute: typeof AuthenticatedImpoundRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/driver': {
      id: '/_authenticated/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof AuthenticatedDriverRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/billing': {
      id: '/_authenticated/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof AuthenticatedBillingRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/statement/$accountId/$month': {
      id: '/statement/$accountId/$month'
      path: '/statement/$accountId/$month'
      fullPath: '/statement/$accountId/$month'
      preLoaderRoute: typeof StatementAccountIdMonthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/inbound-email': {
      id: '/api/public/inbound-email'
      path: '/api/public/inbound-email'
      fullPath: '/api/public/inbound-email'
      preLoaderRoute: typeof ApiPublicInboundEmailRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/approval-action': {
      id: '/api/public/approval-action'
      path: '/api/public/approval-action'
      fullPath: '/api/public/approval-action'
      preLoaderRoute: typeof ApiPublicApprovalActionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedBillingRoute: typeof AuthenticatedBillingRoute
  AuthenticatedDriverRoute: typeof AuthenticatedDriverRoute
  AuthenticatedImpoundRoute: typeof AuthenticatedImpoundRoute
  AuthenticatedInboundEmailsRoute: typeof AuthenticatedInboundEmailsRoute
  AuthenticatedMotorClubsRoute: typeof AuthenticatedMotorClubsRoute
  AuthenticatedRotationsRoute: typeof AuthenticatedRotationsRoute
  AuthenticatedSettingsRoute: typeof AuthenticatedSettingsRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedBillingRoute: AuthenticatedBillingRoute,
  AuthenticatedDriverRoute: AuthenticatedDriverRoute,
  AuthenticatedImpoundRoute: AuthenticatedImpoundRoute,
  AuthenticatedInboundEmailsRoute: AuthenticatedInboundEmailsRoute,
  AuthenticatedMotorClubsRoute: AuthenticatedMotorClubsRoute,
  AuthenticatedRotationsRoute: AuthenticatedRotationsRoute,
  AuthenticatedSettingsRoute: AuthenticatedSettingsRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AcceptInviteRoute: AcceptInviteRoute,
  AdminRoute: AdminRoute,
  ApplyRoute: ApplyRoute,
  AuthRoute: AuthRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  PendingRoute: PendingRoute,
  RejectedRoute: RejectedRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  RequestCompanyIdRoute: RequestCompanyIdRoute,
  ApiPublicApprovalActionRoute: ApiPublicApprovalActionRoute,
  ApiPublicInboundEmailRoute: ApiPublicInboundEmailRoute,
  StatementAccountIdMonthRoute: StatementAccountIdMonthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
